name: Use Repository Variables

on:
  workflow_dispatch: 

jobs:
  use-repo-variables:
    runs-on: ubuntu-latest
    env:
      env_var: ${{ vars.MY_API_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Access Repository Variables
        run: |
          echo "The value of MY_API_KEY is: ${{ vars.MY_API_KEY }}"

      - name: Use Variables in a Script
        run: |
          if [ "${{ vars.APP_ENV }}" == "production" ]; then
            echo "Deploying to production with API key: ${{ vars.MY_API_KEY }}"
          else
            echo "Running in development mode."
          fi

      - name: Mask Sensitive Variables
        env:
          MY_API_KEY: ${{ vars.MY_API_KEY }}
        run: |
          echo "Sensitive API Key: $MY_API_KEY"
