name: Use Repository Secrets

on:
  workflow_dispatch:

jobs:
  use-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Access Repository Secrets
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: |
          echo "Using API Key: $API_KEY"
          echo "Using API Password: $API_PASSWORD"
          # Masking sensitive output is automatic for secrets

      - name: Run a Script with Secrets
        env:
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: |
          echo "Connecting to database with password: $API_PASSWORD"
      - name: Fail If Secret Is Missing
        if: ${{ secrets.API_KEY == null }}
        run: |
          echo "MISSING_SECRET is not defined in the repository."
          exit 1
