name: GitHub Actions Workflow example syntax

run-name: Execute ${{ github.event_name }} Workflow

on:
  push:
    branches:
      - main
      - release/*
    tags:
      - 'v*'
      - 'release-*'
    branches-ignore:
      - 'test/*'
    tags-ignore:
      - 'beta-*'
    paths:
      - 'src/**'
      - 'lib/**'
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - main
      - feature/*
    branches-ignore:
      - 'test/*'
  #schedule:
   # - cron: '0 3 * * *'

jobs:
  example-job:
    name: Example Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log Event Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"
